alias please='sudo'
alias ls='ls -aF --color=always'
alias ll='ls -l'
alias update='sudo apt-get update && sudo apt-get upgrade'
alias actualizator='please ~/.unix-tools/actualizator.sh'
alias dist-upgrade='sudo apt-get update && sudo apt-get dist-upgrade'
alias install='sudo apt-get install'
alias purge='sudo apt-get purge'
alias tarsvn='tar --exclude={.svn,.idea} -z -c -v -f '
alias targit='tar --exclude={.git,.idea} -z -c -v -f '
alias wepcrackeator='please ~/.unix-tools/wepcrackeator.sh'
alias search='please find / -name '
alias httpserver='python -m SimpleHTTPServer'
alias getmyip='curl -s http://ifconfig.me'
alias getdiskspace='df -h'
alias getmemory='free -m'
